# Nav
social:
  Github: https://github.com/lilizhou520

# Background image, color
background: 'url(../img/daisy.jpg) #f3f3f3'

# Favicon
favicon: https://cdn.jsdelivr.net/gh/frontendsophie/hexo-theme-autumn@1.0.0/source/img/favicon.ico

# SEO
keywords: 'lilizhou, github'

# Widgets, enable at least one
widgets:
  category: enabled
  archive: enabled
  tag: enabled

# Set the first image in post to cover
auto_cover: true
auto_excerpt:
  enable: true
  length: 150
